# Generated by Django 6.0.3 on 2026-03-05 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=200, unique=True)),
                ('full_name', models.CharField(default='HRMS_LITE_EMPLOYEE', max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('department', models.CharField(choices=[('HR', 'HR'), ('FINANCE/ACCOUNTING', 'FINANCE/ACCOUNTING'), ('OPERATIONS', 'OPERATIONS'), ('IT', 'IT'), ('R&D', 'R&D'), ('Others', 'Others')], default='Others', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT')], default='ABSENT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
    ]
